export let ActivitySettingsCaptions =
{
    "activityLengthType" : "Activity Duration",
    "competitionMode" : "Competition Mode",
    "distractingPodsColor" : "Distracting Pods Color",
    "homeBasePodColor" : "Home Base Pod Color",
    "lightDelayTimeType" : "Light delay time",
    "lightDelayTimeTypeCornerPods" : "Light delay time for corner Pods",
    "lightDelayTimeTypeHomeBasePod" : "Light delay time for home base Pod",
    "lightsOutType" : "Lights out",
    "lightsOutTypeCornerPods" : "Lights out for corner Pods",
    "lightsOutTypeHomeBasePod" : "Lights out for home base Pod",
    "player" : "Player ", 
    "colors" : "Colors",
    "stepPodColor" : "Step Pod Color",
    "podSelector" : "Pod Selector",
    "strikeOutType" : "Strike out",
    "whistleBeforeCorners" : "Whistle Before Corners",
    "colorsPerPlayer" : "Colors per Player",
    "cornerPodslightsOut" : "Timeout",
    "cycles" : "Cycles",
    "delayCycles" : "Time between cycles",
    "distractingColorsCount" : "Number of distracting colors",
    "distractingPods" : "Number of distracting Pods",
    "duration" : "Duration",
    "hitCount" : "Hit Count",
    "homeBasePodLightsOut" : "Timeout",
    "lightDelayFixed" : "Light delay time",
    "lightDelayFixedCorners" : "Corners light delay time",
    "lightDelayFixedHomeBase" : "Home base light delay time",
    "lightDelayRandomFromCorners" : "Light delay from",
    "lightDelayRandomFromHomeBase" : "Light delay from",
    "lightDelayRandomToCorners" : "Light delay to",
    "lightDelayRandomToHomeBase" : "Light delay to",
    "lightDelayTimeFrom" : "Light delay from",
    "lightDelayTimeTo" : "Light delay to",
    "lightsOut" : "Lights Out",
    "players" : "Players",
    "pods" : "Pods",
    "podsPerPlayer" : "Pods Per Player",
    "repetitions" : "Repetitions",
    "stations" : "Stations",
    "steps" : "Steps",
    "strikeOut" : "Strike Out"
}